services:
  flask-backend:
    build: ./flask-backend
    ports:
      - "5000:5000"
    volumes:
      - ./flask-backend:/app
    environment:
      - FLASK_ENV=development

  react-frontend:
    build: ./react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./react-frontend:/app
    environment:
      - NODE_ENV=development