name: bagseek-cpu
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - flask
  - flask-cors
  - tqdm
  - openpyxl
  - matplotlib
  - opencv
  - pytorch
  - torchvision
  - faiss-cpu
  - pip:
      - open-clip-torch
      - rosbags
      - rosbag2_py
      - rclpy
      - rosidl-runtime-py
      - safetensors