name: bagseek-gpu
channels:
  - rapidsai
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - libnvjitlink
  - faiss-gpu-cuvs=1.11.0
  - pillow
  - pandas
  - psutil
  - matplotlib 
  - pip:
      - blinker==1.9.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.2.1
      - filelock==3.18.0
      - flask==3.1.1
      - fsspec==2025.5.1
      - hf-xet==1.1.3
      - huggingface-hub==0.32.4
      - idna==3.10
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - lz4==4.4.4
      - markupsafe==3.0.2
      - opencv-python==4.11.0.86
      - pip==25.1.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.3
      - tokenizers==0.21.1
      - tqdm==4.67.1
      - transformers==4.52.4
      - typing-extensions==4.14.0
      - urllib3==2.4.0
      - werkzeug==3.1.3